// This file contains the definition of the enumeration types

#if !defined(_ENUM_TYPES_H)
#define _ENUM_TYPES_H

enum CRYSTAL_TYPE_ENUM {SIMPLECUBIC,
						BODYCENTEREDCUBIC,
						FACECENTEREDCUBIC,
						SIMPLETETRAGONAL,
						CENTEREDTETRAGONAL,
						SIMPLEORTHOROMBIC,
						BASECENTEREDORTHOROMBIC,
						BODYCENTEREDORTHOROMBIC,
						FACECENTEREDORTHOROMBIC,
						SIMPLEMONOCLINIC,
						CENTEREDMONOCLINIC,
						TRICLINIC,
						TRIGONAL,
						HEXAGONAL
						};

#endif // !defined(_ENUM_TYPES_H)
