//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Madelung.rc
//
#define IDD_ABOUTBOX                    100
#define ID_AW_GB                        101
#define ID_WIN_ATOMWIN                  102
#define ID_PROGRESS_BAR                 103
#define IDD_PP_EDITATOMS                105
#define IDD_PP_ATOMSINUNITCELL          105
#define IDD_PLOT_UNITCELLS              106
#define IDD_PP_CRYSTAL_LATTICE          107
#define IDD_PP_SPACE_GROUP              107
#define IDR_MAINFRAME                   128
#define IDR_MADELUTYPE                  129
#define IDI_ICON_H                      135
#define IDI_ICON_HE                     136
#define IDI_ICON_LI                     137
#define IDI_ICON_BE                     138
#define IDI_ICON_B                      139
#define IDI_ICON_C                      140
#define IDI_ICON_N                      141
#define IDI_ICON_O                      142
#define IDI_ICON_F                      143
#define IDI_ICON_NE                     144
#define IDI_ICON_NA                     145
#define IDI_ICON_MG                     146
#define IDI_ICON_AL                     147
#define IDI_ICON_SI                     148
#define IDI_ICON_P                      149
#define IDI_ICON_S                      150
#define IDI_ICON_CL                     151
#define IDI_ICON_AR                     152
#define IDI_ICON_K                      153
#define IDI_ICON_CA                     154
#define IDI_ICON_SC                     155
#define IDI_ICON_TI                     156
#define IDI_ICON_V                      157
#define IDI_ICON_CR                     158
#define IDI_ICON_MN                     159
#define IDI_ICON_FE                     160
#define IDI_ICON_CO                     161
#define IDI_ICON_NI                     162
#define IDI_ICON_CU                     163
#define IDI_ICON_ZN                     164
#define IDI_ICON_GA                     165
#define IDI_ICON_GE                     166
#define IDI_ICON_AS                     167
#define IDI_ICON_SE                     168
#define IDI_ICON_BR                     169
#define IDI_ICON_KR                     170
#define IDI_ICON_RB                     171
#define IDI_ICON_SR                     172
#define IDI_ICON_Y                      173
#define IDI_ICON_ZR                     174
#define IDI_ICON_NB                     175
#define IDI_ICON_MO                     176
#define IDI_ICON_TC                     177
#define IDI_ICON_RU                     178
#define IDI_ICON_RH                     179
#define IDI_ICON_PD                     180
#define IDI_ICON_AG                     181
#define IDI_ICON_CD                     182
#define IDI_ICON_IN                     183
#define IDI_ICON_SN                     184
#define IDI_ICON_SB                     185
#define IDI_ICON_TE                     186
#define IDI_ICON_I                      187
#define IDI_ICON_XE                     188
#define IDI_ICON_CS                     189
#define IDI_ICON_BA                     190
#define IDI_ICON_LA                     191
#define IDI_ICON_LU                     192
#define IDI_ICON_HF                     193
#define IDI_ICON_TA                     194
#define IDI_ICON_W                      195
#define IDI_ICON_RE                     196
#define IDI_ICON_OS                     197
#define IDI_ICON_IR                     198
#define IDI_ICON_PT                     199
#define IDI_ICON_AU                     200
#define IDI_ICON_HG                     201
#define IDI_ICON_TL                     202
#define IDI_ICON_PB                     203
#define IDI_ICON_BI                     204
#define IDI_ICON_PO                     205
#define IDI_ICON_AT                     206
#define IDI_ICON_RN                     207
#define IDI_ICON_FR                     208
#define IDI_ICON_RA                     209
#define IDI_ICON_AC                     210
#define IDD_DIALOG_EDIT_ATOM            211
#define IDI_ICON_MOLECULE               212
#define IDD_DIALOG_LATTICE_EXTEND       214
#define IDD_DIALOG_LATTICE_EXTEND_SPHERE 215
#define IDR_START                       216
#define IDD_ATOMWINDOW                  216
#define IDR_MAINFRAME_CANCEL            219
#define IDD_DIALOG_SYMMETRY             221
#define IDD_ADD_ATOM_TO_PLOT            223
#define IDR_POPUP                       227
#define IDD_EDITMOLECULE                228
#define IDD_MOLECULELIST                229
#define IDD_PP_MOLECULESINUNITCELL      229
#define IDD_EDIT_ATOMS_IN_MOLECULE      230
#define IDC_STATIC_UNIT_CELL_PARAMETERS 1000
#define IDC_CLS_TYPE_CUBIC              1001
#define IDC_CLS_TYPE_TETRAGONAL         1002
#define IDC_CLS_TYPE_ORTHOROMBIC        1003
#define IDC_STATIC_CRYSTAL_TYPE2        1004
#define IDC_STATIC_SPACE_GROUP          1004
#define IDC_CLS_TYPE_BCC                1005
#define IDC_CLS_TYPE_FCC                1006
#define IDC_CLS_TYPE_CENTERED_TETRAGONAL 1007
#define IDC_CLS_TYPE_BC_ORTHOROMBIC     1008
#define IDC_CLS_TYPE_BODYCENTERED_ORTHOROMBIC 1009
#define IDC_CLS_TYPE_FC_ORTHOROMBIC     1010
#define IDC_CLS_TYPE_MONOCLINIC         1011
#define IDC_ABC                         1012
#define IDC_CLS_TYPE_CENTERED_MONOCLINIC 1013
#define IDC_CLS_TYPE_TRICLINIC          1014
#define IDC_CLS_TYPE_TRIGONAL           1015
#define IDC_CLS_TYPE_HAXAGONAL          1016
#define IDC_CLS_STATIC_ANGLES           1017
#define IDC_EDIT_X                      1018
#define IDC_EDITATOMS_X                 1018
#define IDC_EDIT_Y                      1019
#define IDC_EDITATOMS_Y                 1019
#define IDC_EDIT_Z                      1020
#define IDC_EDITATOMS_Z                 1020
#define IDC_EDIT_ALPHA                  1021
#define IDC_EDITATOMS_CHARGE            1021
#define IDC_EDIT_BETA                   1022
#define IDC_EDIT_GAMMA                  1023
#define IDC_CLS_STATIC_ATOMSPERUNITCELL 1027
#define IDC_XYZ                         1028
#define IDC_STATIC_XYZ                  1028
#define IDC_PP_EDITATOMS_REMOVEATOM     1029
#define IDC_PP_EDITATOMS_ADDATOM        1030
#define IDC_PP_ATOMSINUNITCELL_ADD      1030
#define IDC_PP_ATOMSINUNITCELL_EDIT     1031
#define IDC_PP_EDITATOMS_REMOVEALL      1032
#define IDC_PP_EDITATOMS_LISTCONTROL    1033
#define IDC_PP_ATOMSINUNITCELL_LISTCONTROL 1033
#define IDC_EDIT_A                      1034
#define IDC_EDIT_B                      1035
#define IDC_EDIT_C                      1036
#define IDC_TAB1                        1037
#define IDC_EDITATOMS_STATIC_CHARGE     1041
#define IDC_RADIO_H                     1042
#define IDC_RADIO_HE                    1043
#define IDC_RADIO_LI                    1044
#define IDC_RADIO_BE                    1045
#define IDC_RADIO_B                     1046
#define IDC_RADIO_C                     1047
#define IDC_RADIO_N                     1048
#define IDC_RADIO_O                     1049
#define IDC_RADIO_F                     1050
#define IDC_RADIO_NE                    1051
#define IDC_RADIO_NA                    1052
#define IDC_RADIO_MG                    1053
#define IDC_RADIO_AL                    1054
#define IDC_RADIO_SI                    1055
#define IDC_RADIO_P                     1056
#define IDC_RADIO_S                     1057
#define IDC_RADIO_CL                    1058
#define IDC_RADIO_AR                    1059
#define IDC_RADIO_K                     1060
#define IDC_RADIO_CA                    1061
#define IDC_RADIO_SC                    1062
#define IDC_RADIO_TI                    1063
#define IDC_RADIO_V                     1064
#define IDC_RADIO_CR                    1065
#define IDC_RADIO_MN                    1066
#define IDC_RADIO_FE                    1067
#define IDC_RADIO_CO                    1068
#define IDC_RADIO_NI                    1069
#define IDC_RADIO_CU                    1070
#define IDC_RADIO_ZN                    1071
#define IDC_RADIO_GA                    1072
#define IDC_RADIO_GE                    1073
#define IDC_RADIO_AS                    1074
#define IDC_RADIO_SE                    1075
#define IDC_RADIO_BR                    1076
#define IDC_RADIO_KR                    1077
#define IDC_RADIO_RB                    1078
#define IDC_RADIO_SR                    1079
#define IDC_RADIO_Y                     1080
#define IDC_RADIO_ZR                    1081
#define IDC_RADIO_NB                    1082
#define IDC_RADIO_MO                    1083
#define IDC_RADIO_TC                    1084
#define IDC_RADIO_RU                    1085
#define IDC_RADIO_RH                    1086
#define IDC_RADIO_PD                    1087
#define IDC_RADIO_AG                    1088
#define IDC_RADIO_CD                    1089
#define IDC_RADIO_IN                    1090
#define IDC_RADIO_SN                    1091
#define IDC_RADIO_SB                    1092
#define IDC_RADIO_TE                    1093
#define IDC_RADIO_I                     1094
#define IDC_RADIO_XE                    1095
#define IDC_RADIO_CS                    1096
#define IDC_RADIO_BA                    1097
#define IDC_RADIO_LA                    1098
#define IDC_RADIO_LU                    1099
#define IDC_RADIO_HF                    1100
#define IDC_RADIO_TA                    1101
#define IDC_RADIO_W                     1102
#define IDC_RADIO_RE                    1103
#define IDC_RADIO_OS                    1104
#define IDC_RADIO_IR                    1105
#define IDC_RADIO_PT                    1106
#define IDC_RADIO_AU                    1107
#define IDC_RADIO_HG                    1108
#define IDC_RADIO_TL                    1109
#define IDC_RADIO_PB                    1110
#define IDC_RADIO_BI                    1111
#define IDC_RADIO_PO                    1112
#define IDC_RADIO_AT                    1113
#define IDC_RADIO_RN                    1114
#define IDC_RADIO_FR                    1115
#define IDC_RADIO_RA                    1116
#define IDC_RADIO_AC                    1117
#define IDC_PT_ELEMENT_NAME             1118
#define IDC_EDITATOM_BUTTON_OK          1119
#define IDC_EDITATOM_BUTTON_CANCEL      1120
#define IDC_EDITATOMS_STATIC_POSITIONS  1123
#define IDC_EDIT_UNITCELLS_A            1125
#define IDC_EDIT_UNITCELLS_B            1126
#define IDC_EDIT_UNITCELLS_C            1127
#define IDC_BUTTON_UNITCELLS_OK         1128
#define IDC_BUTTON_UNITCELLS_CANCEL     1129
#define IDC_SPIN_UNITCELLS_A            1130
#define IDC_SPIN_UNITCELLS_B            1131
#define IDC_STATIC_COMPLEMENT           1131
#define IDC_SPIN_UNITCELLS_C            1132
#define IDC_STATIC_APPEND_A             1132
#define IDC_EDIT_EXTEND_A               1133
#define IDC_EDIT_EXTEND_B               1134
#define IDC_EDIT_EXTEND_C               1135
#define IDC_SPIN_EXTEND_A               1136
#define IDC_SPIN_EXTEND_B               1137
#define IDC_SPIN_EXTEND_C               1138
#define IDC_EDIT_SPHERE_RADIUS          1139
#define IDC_SPIN_SPHERE_RADIUS          1140
#define IDC_BUTTON_EXTEND_OK            1141
#define IDC_BUTTON_EXTEND_CANCEL        1142
#define IDC_BUTTON_SPHERE_OK            1143
#define IDC_BUTTON_SPHERE_CANCEL        1144
#define IDC_RADIO_SPGROUPS_SHORT_HM     1146
#define IDC_RADIO_SPGROUPS_NUMBER       1147
#define IDC_RADIO_SPGROUPS_SCHOENFLIES  1148
#define IDC_RADIO_SPGROUPS_FULL_HM      1149
#define IDC_EDIT_SG                     1150
#define IDC_BUTTON_SGSETUP_LOAD         1151
#define IDC_RADIO_SPGROUPS_HALL         1152
#define IDC_STATIC_SGSETUP_INFO         1153
#define IDC_STATIC_SGSETUP_SG           1154
#define IDC_STATIC_SGSETUP_SGNUMBER     1155
#define IDC_STATIC_SGSETUP_HALLSYMBOL   1156
#define IDC_STATIC_HALLSYMBOLVALUE      1157
#define IDC_STATIC_SGSETUP_POINTGROUP   1158
#define IDC_STATIC_SGSETUP_PGVALUE      1159
#define IDC_STATIC_SGSETUP_CRYSYST      1160
#define IDC_STATIC_SGSETUP_CRYSYSTVALUE 1161
#define IDC_STATIC_SGSETUP_LATTICESYMBOL 1162
#define IDC_STATIC_SGSETUP_LATTICESYMBOLVALUE 1163
#define IDC_STATIC_SGSETUP_ABC_RESTRICTIONS 1164
#define IDC_STATIC_SGSETUP_ANGLE_RESTRICTIONS 1165
#define IDC_STATIC_SGSETUP_SHORT_VALUE  1166
#define IDC_STATIC_SGSETUP_LONG_VALUE   1167
#define IDC_STATIC_SGSETUP_SCH_VALUE    1168
#define IDC_STATIC_EDITATOM_WK          1169
#define IDC_STATIC_SGSETUP_ADDITIONALINFO 1169
#define IDC_STATIC_SGSETUP_ADDITIONALINFOVALUE 1170
#define IDC_LIST_EDITATOM_WYCK          1171
#define IDC_STATIC_SGSETUP_PAGEINTABLES 1171
#define IDC_STATIC_EDITATOM_WYMULT      1172
#define IDC_STATIC_SGSETUP_PAGENUMBER   1172
#define IDC_STATIC_EDITATOM_WYSYMM      1173
#define IDC_EDITATOM_VIEWCOORDINATES    1176
#define IDC_RADIO2                      1181
#define IDC_RADIO3                      1182
#define IDC_RADIO4                      1183
#define IDC_RADIO5                      1184
#define IDC_RADIO6                      1185
#define IDC_RICHEDIT1                   1187
#define IDC_EXTEND_PARAL_CHECK          1188
#define IDC_EXTEND_SPHERE_CHECK         1189
#define IDC_SYMMETRY_STATIC             1190
#define IDC_SYMMETRY_LIST               1191
#define IDC_ADD_ATOM_EDIT               1194
#define IDC_STATIC_PARAL_SYMMETRY       1197
#define IDC_STATIC_SPHERE_SYMMETRY      1198
#define IDC_EDITMOLECULE_ADD            1200
#define IDC_EDITMOLECULE_EDIT           1201
#define IDC_EDITMOLECULE_REMOVEATOM     1202
#define IDC_EDITMOLECULE_REMOVEALL      1203
#define IDC_EDITMOLECULE_LISTCONTROL    1204
#define IDC_MOLECULES_NEW               1205
#define IDC_MOLECULES_EDIT              1206
#define IDC_MOLECULES_REMOVE            1207
#define IDC_MOLECULES_REMOVEALL         1208
#define IDC_MOLECULES_ADD               1209
#define IDC_EDIT1                       1209
#define IDC_EDITMOLECULE_NAME           1209
#define IDC_RADIO_MOLECULE              1210
#define IDC_PP_MOLECULESINUNITCELL_ADD  1216
#define IDC_PP_MOLECULESINUNITCELL_EDIT 1217
#define IDC_PP_MOLECULESINUNITCELL_REMOVE 1218
#define IDC_PP_MOLECULESINUNITCELL_REMOVEALL 1219
#define IDC_EDITMOLECULE_X              1220
#define IDC_EDITMOLECULE_Y              1221
#define IDC_PP_MOLECULESINUNITCELL_LISTCONTROL 1221
#define IDC_EDITMOLECULE_Z              1222
#define IDC_EDITMOLECULE_ALPHA          1223
#define IDC_EDITMOLECULE_BETA           1224
#define IDC_EDITMOLECULE_GAMMA          1225
#define ID_TOOLS_SETUP_LATTICE          32772
#define ID_TOOLS_SETUP_OPTIMIZATION     32774
#define ID_TOOLS_OPTIONS                32775
#define ID_TOOLS_SETUP_LATTICESUMMATION 32781
#define ID_TOOLS_PCDF_STEP              32782
#define ID_TOOLS_PCDF_1                 32782
#define ID_TOOLS_PCDF_2                 32783
#define ID_TOOLS_PCDF_3                 32784
#define ID_TOOLS_PCDF_4                 32785
#define ID_TOOLS_PCDF_5                 32786
#define ID_TOOLS_PCDF_6                 32787
#define ID_TOOLS_PCDF_7                 32788
#define ID_TOOLS_PCDF_8                 32789
#define ID_TOOLS_PCDF_9                 32790
#define ID_TOOLS_POTENTIAL_ON_ATOMS     32792
#define ID_PLOT_UNITCELL                32793
#define ID_TOOLS_SELECTATOMS            32794
#define ID_PLOT_LATTICE                 32795
#define ID_ISOSURFACES                  32796
#define ID_TOOLS_ROTATEATOMS            32797
#define ID_VIEW_BONDS                   32800
#define ID_TOOLS_EXTEND_NORMAL          32801
#define ID_TOOLS_EXTEND_SPHERE          32802
#define ID_TOOLS_EXTEND_DELETE          32803
#define ID_VIEW_CELLBORDERS             32804
#define ID_VIEW_WYCKOFF                 32805
#define ID_TOOLS_UNSELECTALLATOMS       32806
#define ID_CANCEL_CALCULATION           32807
#define ID_VIEW_OUTPUT                  32808
#define ID_OPTIMIZE                     32809
#define ID_TOOLS_SYMMETRY               32810
#define ID_PLOT_ATOM                    32811
#define ID_PLOT_ATOM_REMOVE             32812
#define ID_POPUP_SELECT                 32813
#define ID_POPUP_HIDE                   32814
#define ID_POPUP_HIDEALL                32815
#define ID_POPUP_UNSELECT               32816
#define IDR_POPUP_SELECTATOM            32821
#define IDR_POPUP_UNSELECTATOM          32822
#define IDR_POPUP_HIDE                  32823
#define IDR_POPUP_HIDEALL               32824
#define ID_POPUP_DESELECT               32825
#define IDR_POPUP_SHOWALL               32826
#define ID_COMPUTE_DECOMPOSE            32827
#define IDR_POPUP_HIDELAYER_X           32828
#define IDR_POPUP_HIDELAYER_Y           32829
#define IDR_POPUP_HIDELAYER_Z           32830

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        232
#define _APS_NEXT_COMMAND_VALUE         32831
#define _APS_NEXT_CONTROL_VALUE         1222
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
